### ISSUE TITLE
Stars visible in master flats

### ISSUE THREAD

**Issue by danjampro** [AstroHuntsman/huntsman-drp#153]
Stars appear visible in some master flats. Not good!

**Comment by danjampro** [comment]
Looking at the LSST flat field code:

https://github.com/lsst/pipe_drivers/blob/d00fb1e517e6e177fc9fbe9285921bb8515ad3ae/python/lsst/pipe/drivers/constructCalibs.py#L644

It looks like it calls only `ISRTask`, which performs the steps outlined here:

https://github.com/lsst/ip_isr/blob/535a0ce822ab4f2679c4e32ff5a3617ff778b991/python/lsst/ip/isr/isrTask.py#L1229

So there is no explicit source masking. There is a default sigma-clipping algorithm applied during combination:

https://github.com/lsst/pipe_drivers/blob/d00fb1e517e6e177fc9fbe9285921bb8515ad3ae/python/lsst/pipe/drivers/constructCalibs.py#L91

But that doesn’t seem to be working as intended. Suggested solution is to modify `FlatTask.processSingle` to include a multi-scale filter masking procedure.

**Comment by danjampro** [comment]
Suggestion for implementing multi scale filtering is to use `MaskObjectsTask` several times with different smoothing lengths:

https://github.com/lsst/pipe_drivers/blob/d00fb1e517e6e177fc9fbe9285921bb8515ad3ae/python/lsst/pipe/drivers/background.py#L770

**Comment by fergusL** [comment]
![starflats](https://user-images.githubusercontent.com/35693293/120589768-b5cc8380-c47c-11eb-96fb-5c55a8c908b7.png)

**Comment by fergusL** [comment]
![zoom](https://user-images.githubusercontent.com/35693293/120590664-39d33b00-c47e-11eb-8ca5-e6a497e0314e.png)
